# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: []
  behavior: default
  flags: []
  paths: []
ignore:
  - "examples/"
  - "docs/"
