name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Weekly tests at midnight on Sundays run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  main-tests:
    if: "github.repository == 'yoshanuikabundi/openff-pablo'"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.11", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build information
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        run: |
          python --version
          python -m pip install .

      - name: Python information
        run: |
          which python
          which pip
          pip list
          micromamba info
          micromamba list

      - name: Lint
        run: |
          ruff check openff

      - name: Type check
        run: |
          basedpyright openff

      - name: Run tests
        run: |
          pytest -n 2 -v --cov=openff-pablo --cov-report=xml --color=yes openff/pablo/_tests/

    # - name: codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: coverage.xml
    #     name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
    #     verbose: True
