name: GH Actions Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Weekly tests at midnight on Sundays run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  lints:
    if: "github.repository == 'openforcefield/openff-pablo'"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build information
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.40.3
          environments: test

      - run: pixi run test -v --color=yes --cov=openff/pablo --cov-append --cov-report=xml

      - run: pixi run doctest -v --color=yes

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          disable_search: true
          fail_ci_if_error: false
